import { Request, Response, NextFunction } from "express";
import {
  GROQ_VISION_MODEL,
  groqChatCompletion,
  parseJsonFromModel,
} from "../config/groq.ts";
import { extractPdfTextFromDataUrl, isPdfUpload } from "../lib/extractPdfText.ts";

function parseDataUrl(dataUrl: string) {
  const matches = dataUrl.match(/^data:([^;]+);base64,(.+)$/);
  if (matches) {
    return {
      mimeType: matches[1],
      base64Data: matches[2],
    };
  }
  return null;
}

/**
 * Analyze dropped file content (text, PDF, or image) via Groq.
 * PDFs are text-extracted first so the tutor can ground on real page content.
 */
export async function analyzeFileContent(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { fileText, fileDataUrl, fileName } = req.body;

    if (!fileText && !fileDataUrl) {
      res.status(400).json({ error: "Missing file content text or image dataUrl in request body." });
      return;
    }

    const systemInstruction = `You are an academic curriculum coordinator and expert study guide author. Analyze lecture notes, document text, transcripts, or images and return ONLY valid JSON:
{
  "title": "concise formal academic title",
  "subject": "academic subject category",
  "summary": "one sentence summary",
  "content": "markdown study guide (detailed for images; brief/empty for text uploads)"
}

Be accurate and academic. Avoid generic names like "Lecture" or "Document".`;

    const parsed = fileDataUrl ? parseDataUrl(fileDataUrl) : null;
    let resolvedText = typeof fileText === "string" ? fileText : "";
    let extractedText = "";
    let usedPdfExtraction = false;

    if (parsed && isPdfUpload(parsed.mimeType, fileName)) {
      try {
        extractedText = await extractPdfTextFromDataUrl(fileDataUrl);
        usedPdfExtraction = true;
        if (extractedText) {
          resolvedText = extractedText;
        }
      } catch (err) {
        console.error("PDF text extraction failed:", err);
      }
    }

    let userContent: string | Array<{ type: string; text?: string; image_url?: { url: string } }>;
    let model: string | undefined;

    if (usedPdfExtraction) {
      const pdfBody = resolvedText
        ? resolvedText.slice(0, 20000)
        : "(No selectable text was found in this PDF. It may be a scanned/image-only document.)";

      userContent = `Analyze this uploaded PDF lecture material.
Original file name: "${fileName || "uploaded.pdf"}"

=== PDF EXTRACTED TEXT START ===
${pdfBody}
=== PDF EXTRACTED TEXT END ===

Suggest title, subject, summary, and a useful markdown study guide in "content" grounded in the extracted text when available.`;
    } else if (parsed) {
      model = GROQ_VISION_MODEL;
      userContent = [
        {
          type: "text",
          text: `Analyze this uploaded document/lecture material.
Original file name: "${fileName || "uploaded_image.png"}"

This is a visual/multimodal file. Transcribe visible text, explain diagrams/equations, and put a detailed markdown study guide in "content".`,
        },
        {
          type: "image_url",
          image_url: { url: fileDataUrl },
        },
      ];
    } else {
      userContent = `Analyze this uploaded document/lecture material.
Original file name: "${fileName || "uploaded_notes.txt"}"

=== DOCUMENT CONTENT START ===
${resolvedText.slice(0, 15000)}
=== DOCUMENT CONTENT END ===

Suggest title, subject, summary, and optional content outline.`;
    }

    const text = await groqChatCompletion({
      model,
      messages: [
        { role: "system", content: systemInstruction },
        { role: "user", content: userContent as any },
      ],
      temperature: 0.3,
      json: true,
    });

    const analysisResult = parseJsonFromModel(text) as any;
    if (!analysisResult?.title || !analysisResult?.subject) {
      throw new Error("No suggestion generated by AI model.");
    }

    res.json({
      title: analysisResult.title,
      subject: analysisResult.subject,
      summary: analysisResult.summary || "",
      content: analysisResult.content || "",
      extractedText: extractedText || undefined,
    });
  } catch (error: any) {
    next(error);
  }
}
